export { config, createAuthenticatedClient, createConvexClient } from "./config";
export { AuthProvider, useAuth } from "./context";
export {
  useArchiveProject,
  useCheckProPlan,
  useCreateEnvironment,
  useCreateFolder,
  useCreateProject,
  useCreateSecret,
  useCurrentUser,
  useDeleteEnvironment,
  useDeleteFolder,
  useDeleteSecret,
  useDeviceAuth,
  useEnvironmentData,
  useGetProjectShare,
  useGetProPlan,
  useGetSecret,
  useHasUserKeys,
  useListProjectShares,
  useListSharedProjects,
  useProject,
  useProjects,
  useRevokeShare,
  useRevokeShareWithRotation,
  useRotateUserKeys,
  useSession,
  useShareProject,
  useStoreUserKeys,
  useUnarchiveProject,
  useUpdateEnvironment,
  useUpdateFolder,
  useUpdatePassword,
  useUpdateProject,
  useUpdateSecret,
} from "./hooks";
export type { DeviceAuthCallbacks, DeviceAuthResult } from "./services";
export {
  apiClient,
  clearSession,
  DeviceAuthService,
  deviceAuth,
  ensureValidJwt,
  fetchJwtToken,
  getJwtToken,
  getOrRefreshJwtToken,
  getSessionToken,
  hasValidSession,
  loadSession,
  saveSession,
  updateSessionJwt,
  validateSession,
} from "./services";
export type {
  DeviceAuthStatus,
  DeviceCodeResponse,
  DeviceTokenResponse,
  Session,
  SessionValidation,
} from "./types";
export {
  isAuthorizationDenied,
  isAuthorizationPending,
  isConvexError,
  isDeviceCodeExpired,
} from "./types";
