// This file is auto-generated. Do not edit this file manually.
// To regenerate the schema, run:
// `npx @better-auth/cli generate --output generatedSchema.ts -y`

import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export const tables = {
  user: defineTable({
    name: v.string(),
    email: v.string(),
    emailVerified: v.boolean(),
    image: v.optional(v.union(v.null(), v.string())),
    createdAt: v.number(),
    updatedAt: v.number(),
    userId: v.optional(v.union(v.null(), v.string())),
    freeOrganizationUsed: v.boolean(),
    hasPro: v.boolean(),
    planDowngradedAt: v.optional(v.union(v.null(), v.number())),
    publicKey: v.optional(v.union(v.null(), v.string())),
    encryptedPrivateKey: v.optional(v.union(v.null(), v.string())),
    salt: v.optional(v.union(v.null(), v.string())),
  })
    .index("email_name", ["email", "name"])
    .index("name", ["name"])
    .index("userId", ["userId"]),
  session: defineTable({
    expiresAt: v.number(),
    token: v.string(),
    createdAt: v.number(),
    updatedAt: v.number(),
    ipAddress: v.optional(v.union(v.null(), v.string())),
    userAgent: v.optional(v.union(v.null(), v.string())),
    userId: v.string(),
    activeOrganizationId: v.optional(v.union(v.null(), v.string())),
  })
    .index("expiresAt", ["expiresAt"])
    .index("expiresAt_userId", ["expiresAt", "userId"])
    .index("token", ["token"])
    .index("userId", ["userId"]),
  account: defineTable({
    accountId: v.string(),
    providerId: v.string(),
    userId: v.string(),
    accessToken: v.optional(v.union(v.null(), v.string())),
    refreshToken: v.optional(v.union(v.null(), v.string())),
    idToken: v.optional(v.union(v.null(), v.string())),
    accessTokenExpiresAt: v.optional(v.union(v.null(), v.number())),
    refreshTokenExpiresAt: v.optional(v.union(v.null(), v.number())),
    scope: v.optional(v.union(v.null(), v.string())),
    password: v.optional(v.union(v.null(), v.string())),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("accountId", ["accountId"])
    .index("accountId_providerId", ["accountId", "providerId"])
    .index("providerId_userId", ["providerId", "userId"])
    .index("userId", ["userId"]),
  verification: defineTable({
    identifier: v.string(),
    value: v.string(),
    expiresAt: v.number(),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("expiresAt", ["expiresAt"])
    .index("identifier", ["identifier"]),
  jwks: defineTable({
    publicKey: v.string(),
    privateKey: v.string(),
    createdAt: v.number(),
  }),
  deviceCode: defineTable({
    deviceCode: v.string(),
    userCode: v.string(),
    userId: v.optional(v.union(v.null(), v.string())),
    expiresAt: v.number(),
    status: v.string(),
    lastPolledAt: v.optional(v.union(v.null(), v.number())),
    pollingInterval: v.optional(v.union(v.null(), v.number())),
    clientId: v.optional(v.union(v.null(), v.string())),
    scope: v.optional(v.union(v.null(), v.string())),
  }),
  organization: defineTable({
    name: v.string(),
    slug: v.optional(v.union(v.null(), v.string())),
    logo: v.optional(v.union(v.null(), v.string())),
    createdAt: v.number(),
    metadata: v.optional(v.union(v.null(), v.string())),
    isFreeWithProPlan: v.boolean(),
    currentKeyVersion: v.number(),
    subscriptionStatus: v.string(),
    paymentExpiresAt: v.optional(v.union(v.null(), v.number())),
    paymentLapsedAt: v.optional(v.union(v.null(), v.number())),
    suspendedAt: v.optional(v.union(v.null(), v.number())),
  })
    .index("name", ["name"])
    .index("slug", ["slug"]),
  member: defineTable({
    organizationId: v.string(),
    userId: v.string(),
    role: v.string(),
    createdAt: v.number(),
    wrappedOrgKey: v.optional(v.union(v.null(), v.string())),
    keyVersion: v.optional(v.union(v.null(), v.number())),
    grantedBy: v.string(),
    revokedAt: v.optional(v.union(v.null(), v.number())),
    revokedBy: v.optional(v.union(v.null(), v.string())),
    revocationReason: v.optional(v.union(v.null(), v.string())),
    isPending: v.boolean(),
  })
    .index("organizationId_userId", ["organizationId", "userId"])
    .index("userId", ["userId"])
    .index("role", ["role"]),
  invitation: defineTable({
    organizationId: v.string(),
    email: v.string(),
    role: v.string(),
    status: v.string(),
    expiresAt: v.number(),
    inviterId: v.string(),
  })
    .index("email_organizationId_status", ["email", "organizationId", "status"])
    .index("organizationId_status", ["organizationId", "status"])
    .index("status", ["status"])
    .index("inviterId", ["inviterId"]),
};

const schema = defineSchema(tables);

export default schema;
